version: '3'

services:
  beammp-server:
    #If you're using Mac M1 or some other ARM based CPU, this is needed to make server work
    platform: linux/amd64
    container_name: ${SERVER_CONTAINER_NAME}
    image: beammp-server
    build:
      context: ./BeamMP
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "30814:30814"
      - "30814:30814/udp" 
      - "8080:8080"
    volumes:
      - shared:/root/beammp
    networks:
      beammp-network:
        ipv4_address: 172.69.69.2

  back-py-end:
    container_name: beammp-py-backend
    image: beammp-py-backend
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      #Dev volume
      - ./BackEnd/Python-src:/app/
      #Prod volume
      - shared:/root/shared
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      beammp-network:
        ipv4_address: 172.69.69.3

  front-end:  
    container_name: beammp-webui
    image: beammp-webui
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "8082:80"
    networks:
      beammp-network:
        ipv4_address:  172.69.69.4


networks:
  beammp-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.69.69.0/24

volumes:
  shared:
    driver: local
    driver_opts:
      type: none
      device: ./BeamMP/Server/
      o: bind

  
