[HTTP]
HTTPServerEnabled = true
UseSSL = false
HTTPServerIP = "0.0.0.0"
HTTPServerPort = 8080
SSLCertPath = "./.ssl/HttpServer/cert.pem"
SSLKeyPath = "./.ssl/HttpServer/key.pem"

[Misc]
SendErrorsShowMessage = true
SendErrors = true
ImScaredOfUpdates = true

[General]
Description = "BeamMP Default Description"
ResourceFolder = "Resources"
Map = "/levels/GridMap/info.json"
MaxPlayers = 8
Port = 30814
Private = true
Debug = true
Name = "BeamMP Server"
LogChat = true
MaxCars = 3
AuthKey = "10"
